blueprints/post/models.py
import datetime as dt
from peewee import *
from blueprints.user.models import User


db = SqliteDatabase('database.db')


class Post(Model):
    user = ForeignKeyField(User, backref='posts')
    text = TextField()
    date = DateTimeField(default=dt.datetime.now)

    class Meta:
        database = db

    @property
    def post_date(self):
        return self.date.strftime('%Y-%m-%d %H:%M:%S')

blueprints/user/models.py
from peewee import *


db = SqliteDatabase('database.db')


class User(Model):
    name = CharField(max_length=50)
    email = CharField(max_length=150, unique=True)
    password = CharField(max_length=100)

    class Meta:
        database = db

blueprints/post/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import TextAreaField
from wtforms.validators import DataRequired, Length


class PostForm(FlaskForm):
    text = TextAreaField('text', validators=[DataRequired(), Length(min=20, max=500)])

app.py
from flask import Flask, render_template
from blueprints.user.models import User
from blueprints.post.models import Post
from blueprints.auth.views import bp as bp_auth
from blueprints.post.views import bp as bp_post


app = Flask(__name__)
app.secret_key = 'qwerty123'
app.debug = True


@app.route('/')
def home():
    from blueprints.post.forms import PostForm
    form = PostForm()
    posts = Post.select().order_by(Post.date.desc())
    return render_template('home.html', form=form, posts=posts)


User.create_table()
Post.create_table()


app.register_blueprint(bp_auth)
app.register_blueprint(bp_post)


# home -> all posts from all users
# user blueprint -> all posts from selected user / ...
# auth blueprint -> login / logout / register

blueprints/post/views.py
from flask import Blueprint, flash, session, url_for, redirect
from .models import Post
from .forms import PostForm


bp = Blueprint('post', __name__, url_prefix='/post')


@bp.route('/', methods=['POST'])
def make_post():
    form = PostForm()

    if form.is_submitted():
        Post.create(
            user_id=session.get('user_id'),
            text=form.text.data
        )
        flash('Post created successfully', 'success')
        return redirect(url_for('home'))

    flash('Something is wrong with post...', 'danger')
    return redirect(url_for('home'))

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Flask Twitter App</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{{ url_for('static', filename='css/album.css') }}" rel="stylesheet">
  </head>

  <body>

    {% include "shared/header.html" %}

    <main role="main">
    {% block main %}
    {% endblock %}
    </main>

    {% include "shared/footer.html" %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{{ url_for('static', filename='js/jquery-3.5.1.slim.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/holder.min.js') }}"></script>
  </body>
</html>

templates/base_without_footer.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Flask Twitter App</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{{ url_for('static', filename='css/album.css') }}" rel="stylesheet">
  </head>

  <body>

    {% include "shared/header.html" %}

    <main role="main">
    {% block main %}
    {% endblock %}
    </main>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{{ url_for('static', filename='js/jquery-3.5.1.slim.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/holder.min.js') }}"></script>
  </body>
</html>

templates/home.html
{% extends "base.html" %}

{% block main %}

{% if session.is_logged_in %}
{% include "shared/post.html" %}
{% endif %}

<div class="album py-5 bg-light">
  <div class="container">

    <div class="row">
      {% for post in posts %}
      {% include "shared/post_card.html" %}
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

templates/shared/flash.html
{% with messages = get_flashed_messages(with_categories=True) %}
  {% if messages %}
    {% for category, message in messages %}
      <div class="alert alert-{{ category }}">
        {{ message }}
      </div>
    {% endfor %}
  {% endif %}
{% endwith %}

{% if form.errors %}
<div class="alert alert-danger">
  {% for field, errors in form.errors.items() %}
    <p>{{ field }}</p>
    <ul>
    {% for error in errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endfor %}
</div>
{% endif %}

templates/shared/footer.html
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
    <p>Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
    <p>New to Bootstrap? <a href="../../">Visit the homepage</a> or read our <a href="../../getting-started/">getting started guide</a>.</p>
  </div>
</footer>

templates/shared/header.html
<header>
  <nav class="navbar navbar-expand navbar-dark bg-dark">
    <div class="container">

      <a class="navbar-brand" href="{{ url_for('home') }}">Twinstagram</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          {% if not session.is_logged_in %}
            <li class="nav-item {% if request.path == url_for('auth.login') %} active {% endif %}">
              <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
            </li>
            <li class="nav-item {% if request.path == url_for('auth.register') %} active {% endif %}">
              <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
            </li>
          {% endif %}
        </ul>
      </div>

    </div>
  </nav>
</header>

templates/shared/post.html
<section class="jumbotron text-center">
  <div class="container">
    <div class="row mt-4 d-flex justify-content-center">
      <div class="col-md-8">
        {{ form.csrf_token() }}

        <form action="{{ url_for('post.make_post') }}" method="post">
          {% include "shared/flash.html" %}

          <div class="form-group mb-4">
            <label for="exampleFormControlTextarea1">Make a new post</label>
            <textarea name="text" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
          </div>

          <button class="btn btn-lg btn-primary btn-block" type="submit">Make post</button>
        </form>

      </div>
    </div>
  </div>
</section>

templates/shared/post_card.html
<div class="col-md-4">
  <div class="card mb-4 box-shadow">
    <div class="card-body">
      <p class="card-text">
        {{ post.text }}
      </p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <button type="button" class="btn btn-sm btn-outline-secondary">Like</button>
        </div>
        <small class="text-muted">
          {{ post.user.email }}
        </small>
        <small class="text-muted">
          {{ post.post_date }}
        </small>
      </div>
    </div>
  </div>
</div>